# ------------------------------------------------------------------------------
# backup_client/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_tasks: install.yml

- ansible.builtin.import_tasks: configure.yml
