- block:

    - name: Add imap and smtp entries to DNS service (home domain)
      ansible.builtin.lineinfile:
        path: /etc/addn-hosts
        line: "{{ mail_server_address }} imap smtp"
      when: domain.name == home_domain

  become: yes
