# ------------------------------------------------------------------------------
# mail/tasks/create-mail-user.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_tasks: create-mail-user-handler.yml

- ansible.builtin.import_tasks: create-mail-user-body.yml
