- block:

  - name: Fix Dropbox folder permissions
    ansible.builtin.file:
      path: ~bacula/Dropbox/
      mode: u=rwx,g=rx,o=

  - name: Determine the current status of the Dropbox daemon
    ansible.builtin.shell: gosu bacula bash -c '~/dropbox.py status'
    register: dropbox_daemon_status
    changed_when: false

  - name: Report the current status of the Dropbox daemon
    ansible.builtin.debug:
      msg: Dropbox status={{ dropbox_daemon_status.stdout }}

  - name: Start Dropbox daemon and wait a little
    ansible.builtin.shell: |-
      gosu bacula bash -c '~/dropbox.py start'
      sleep 60
    when: dropbox_daemon_status.stdout == "Dropbox isn't running!"

  - name: Find what we need to exclude
    ansible.builtin.find:
      paths: ~bacula/Dropbox/
      file_type: directory
      excludes:
        - "{{ backup_copy_folder }}"
    register: to_exclude

  - name: Exclude directories
    ansible.builtin.shell: >-
      gosu bacula bash -c
      '~/dropbox.py
      exclude add "{{ item.path }}"'
    loop: "{{ to_exclude['files'] }}"
    loop_control:
      label: "{{ item.path }}"
    register: exclusions

  - name: Confirm that the syncrhonisation exclusions have been added
    ansible.builtin.debug:
      msg: "{{ item.stdout }}"
    loop: "{{ exclusions['results'] }}"
    loop_control:
      label: "{{ item.item.path }}"
    when: item.skipped is not defined

  become: yes
