- name: Install apt package(s) required for the backup dropbox role
  ansible.builtin.apt:
    name:
      - ca-certificates
      - gosu
      - python3
      - wget

- name: Create backup archive media directory
  ansible.builtin.file:
    path: "{{ backup_archive_media_directory }}"
    state: directory
    owner: bacula
    group: bacula

- name: Install Dropbox Headless
    cmd: >
  ansible.builtin.shell:
      gosu bacula bash -c
      'cd /var/lib/bacula &&
      wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64"
      | tar xzf -'
    creates: /var/lib/bacula/.dropbox-dist

- name: Install Dropbox python helper script
    url: https://www.dropbox.com/download?dl=packages/dropbox.py
    dest: /var/lib/bacula
  ansible.builtin.get_url:
    owner: bacula
    group: bacula
    mode: 0755

# NOTE: There is no point configuring Dropbox to autostart at login.
# This step is present in the Dropbox install instructions but then we're not
# using it in an interactive account here so it's irrelevant.
#- name: Configure Dropbox to autostart at login
#  shell: gosu bacula bash -c '~/dropbox.py autostart y'
