# ------------------------------------------------------------------------------
# backup_dropbox/tasks/main.yml
# ------------------------------------------------------------------------------

---

- block:

  - name: Install apt package(s) required for the backup dropbox role
    ansible.builtin.apt:
      name:
        - ca-certificates
        - gosu
        - python3
        - wget
      install_recommends: no

  - name: Create backup archive media directory
    ansible.builtin.file:
      path: "{{ backup_archive_media_directory }}"
      state: directory
      owner: bacula
      group: bacula

  - name: Install Dropbox Headless
    ansible.builtin.shell:
      cmd: >-
        gosu bacula bash -c
        'cd ~ &&
        wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64"
        | tar xzf -'
      creates: ~bacula/.dropbox-dist/dropboxd

  - name: Ensure we can monitor entire Dropbox folder hierarchy
    ansible.builtin.lineinfile:
      path: /etc/sysctl.conf
      line: fs.inotify.max_user_watches=100000
    notify: sysctl configuration changed

  # NOTE: For some reason this request intermittently gives a 404 response. If
  # this occurs the simply run the playbook again, since the issue will resolve
  # itself at random.
  - name: Install Dropbox python helper script
    ansible.builtin.get_url:
      url: https://linux.dropbox.com/packages/dropbox.py
      dest: ~bacula/dropbox.py
      owner: bacula
      group: bacula
      mode: 0755

  become: yes
