# ------------------------------------------------------------------------------
# calendar/tasks/create-calendars.yml
# ------------------------------------------------------------------------------

---

- name: Create a shared calendar for the office and one for each office user
  ansible.builtin.include_tasks: create-calendar-for-user.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: user
  vars:
    # Define shared_user to associate a shared, office calendar with.
    shared_user:
      username: office
    # Merge shared_user in with the list of office_users, which are the staff.
    users: "{{ [shared_user] + office_users }}"
