---

- block:

    - name: Import wordpress_nginx and site_wordpress roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - wordpress_nginx
        - site_wordpress

    - name: Make Nginx site configuration available
      ansible.builtin.template:
        src: server.j2
        dest: "/etc/nginx/sites-available/{{ wordpress_site_server_name }}"
      notify: Nginx configuration changed

    - name: Enable Nginx site configuration
      ansible.builtin.file:
        src: /etc/nginx/sites-available/{{ wordpress_site_server_name }}
        path: /etc/nginx/sites-enabled/{{ wordpress_site_server_name }}
        state: link
      notify: Nginx configuration changed

  become: yes
