# ------------------------------------------------------------------------------
# mail/handlers/main.yml
# ------------------------------------------------------------------------------

---

- name: Reload the Dovecot configuration when it has changed
  ansible.builtin.service:
    name: dovecot
    state: reloaded
  become: yes
  listen: Dovecot configuration changed
