# ------------------------------------------------------------------------------
# backup_director/tasks/link-to-dropbox.yml
# ------------------------------------------------------------------------------

---

- name: Deploy check-director-dropbox-status.sh script
  ansible.builtin.copy:
    src: check-director-dropbox-status.sh
    dest: /etc/bacula/scripts/
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: yes

- ansible.builtin.import_role:
    name: backup_dropbox
