# ------------------------------
# backup_director/tasks/main.yml
# ------------------------------

---

- ansible.builtin.import_role:
    name: mta

- ansible.builtin.import_tasks: install-service.yml

- ansible.builtin.import_tasks: create-catalog.yml

- ansible.builtin.import_tasks: configure-service.yml
