# ------------------------------------------------------------------------------
# dns/tasks/site/create.yml
# ------------------------------------------------------------------------------

- name: Create DNS entries for WordPress site
  ansible.builtin.lineinfile:
    path: /etc/addn-hosts
    line: >-
      {{ ansible_default_ipv4.address }}
      {{ wordpress_site_subdomain }}.{{ domain_name }}
  notify: Dnsmasq configuration changed
  become: yes
