# ------------------------------------------------------------------------------
# backup_web/tasks/configure-service.yml
# ------------------------------------------------------------------------------

---

- block:

    - name: Template out the bacula_web configuration file
      ansible.builtin.template:
        src: config.php.j2
        dest: /var/www/backup.{{ domain_name }}/application/config/config.php
        owner: www-data
        group: www-data

    - name: Template out config file for nginx site
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/backup.{{ domain_name }}.conf
      notify: Nginx configuration changed

    - name: Enable site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/backup.{{ domain_name }}.conf
        src: /etc/nginx/sites-available/backup.{{ domain_name }}.conf
        state: link
      notify: Nginx configuration changed

  become: yes
