# ------------------------------------------------------------------------------
# backup_web/tasks/install-service.yml
# ------------------------------------------------------------------------------

---

- name: Find if the bacula-web project has already been created
  ansible.builtin.stat:
    path: /var/www/backup.{{ domain_name }}/
  register: bacula_web

- block:

    - name: Install APT packages for backup_web role
      ansible.builtin.apt:
        name:
          - acl
          - ca-certificates
          - composer
          - git
          - gosu
          - php-cli
          - php-mbstring
          - php-mysql
          - php-sqlite3
          - php-xml
          - php-zip
          - unzip
          - wget
        install_recommends: no
      notify: PHP FPM configuration changed

    - name: Enable write in /var/www for the www-data user
      # Composer can not be run as root non-interactively since running as root
      # triggers a prompt for confirmation. So we run it as www-data and
      # therefore must enabled write within /var/www for that user.
      ansible.builtin.file:
        path: /var/www
        group: www-data
        mode: g+w

    - name: Create the bacula-web project
      community.general.composer:
        command: create-project
        arguments: bacula-web/bacula-web backup.{{domain_name}}/
        no_dev: true
        prefer_dist: true
        working_dir: /var/www
      become_user: www-data
      when: not bacula_web.stat.exists

  become: yes
