# ------------------------------------------------------------------------------
# dns/tasks/create-project-record.yml
# ------------------------------------------------------------------------------

# Create a project DNS record. These are added at the bottom of the
# /etc/addn-hosts file, after the line '# Project records'.

---

- name: Create project DNS record
  ansible.builtin.lineinfile:
    path: /etc/addn-hosts
    line: |-
      {% if dns_record_target is defined %}
      {{ hostvars[dns_record_target].ansible_default_ipv4.address }}
      {%- else %}
      {{ ansible_default_ipv4.address }}
      {%- endif %} {{ dns_record_hostname }}
    regexp: >-
      ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}
      {{ dns_record_hostname | regex_escape() }}$
  notify: Dnsmasq configuration changed
  become: yes
