# ------------------------------------------------------------------------------
# dns/tasks/site/create.yml
# ------------------------------------------------------------------------------

- ansible.builtin.import_role:
    name: wordpress
    tasks_from: site_vars

- name: Create DNS entries for WordPress site
  ansible.builtin.lineinfile:
    path: /etc/addn-hosts
    line: "{{ ansible_default_ipv4.address }} {{ wordpress_site_server_name }}"
    regexp: >-
      ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}
      {{ wordpress_site_server_name | regex_escape() }}$

  notify: Dnsmasq configuration changed
  become: yes
