# ------------------------------------------------------------------------------
# dns/tasks/site/delete.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: wordpress
    tasks_from: site_vars

- name: Remove DNS entries for WordPress site
  ansible.builtin.lineinfile:
    path: /etc/addn-hosts
    line: >-
      {{ ansible_default_ipv4.address }}
      {{ wordpress_site_server_name }}
    state: absent
  notify: Dnsmasq configuration changed
  become: yes
