- ansible.builtin.include_role:
    name: dns
    tasks_from: none
    handlers_from: "{{ handlers_from }}"

- name: Delete project DNS record
  ansible.builtin.lineinfile:
    path: /etc/addn-hosts
    line: |-
      {% if dns_record_target is defined %}
      {{ hostvars[dns_record_target].ansible_default_ipv4.address }}
      {%- else %}
      {{ ansible_default_ipv4.address }}
      {%- endif %} {{ dns_record_hostname }}
    state: absent
  notify: Dnsmasq configuration changed
  become: yes
