- block:

    - name: Include DNS role handlers
      ansible.builtin.import_role:
        name: dns
        tasks_from: none.yml
        handlers_from: delegated.yml
      vars:
        delegated_dns_host: "{{ wordpress_site_dns_host }}"

    - name: Remove DNS entries for WordPress site
      ansible.builtin.lineinfile:
        path: /etc/addn-hosts
        line: >-
          {{ ansible_default_ipv4.address }}
          {{ wordpress_site_subdomain }}.{{ domain_name }}
        state: absent
      notify: dnsmasq configuration changed

  become: yes
