- block:

  - name: Add imap entry to DNS service for the home domain only
    ansible.builtin.lineinfile:
      path: /etc/addn-hosts
      line: "{{ hostvars[mail_internal_host].ansible_host }} imap"
    when: domain_name == home_domain
    notify: dnsmasq configuration changed

  become: yes
