# ------------------------------------------------------------------------------
# dns/tasks/home-imap.yml
# ------------------------------------------------------------------------------

# Clients on the home network retrieve their emails from the host for the
# mail_internal_host role. Add an entry to the home network's DNS service for
# the associated, required imap service lookup.

---

- name: Add imap entry to DNS service for the home domain only
  ansible.builtin.lineinfile:
    path: /etc/addn-hosts
    line: "{{ hostvars[mail_internal_host].ansible_host }} imap"
  when: domain_name == home_domain
  notify: Dnsmasq configuration changed
  become: yes
