# ------------------------------------------------------------------------------
# dns/tasks/install-service.yml
# ------------------------------------------------------------------------------

---

- name: Install APT package(s) required by the dns role
  ansible.builtin.apt:
    name:
      - dnsmasq
    install_recommends: no
  become: yes
