- name: Deploy the DNS internal role
  block:

    - name: Install APT package(s) required by the DNS internal role
      ansible.builtin.apt:
        install_recommends: no
        update_cache: yes
        name:
          - dnsmasq

    - name: Template out upstream-resolv.conf
      ansible.builtin.template:
        src: upstream-resolv.conf.j2
        dest: /etc/upstream-resolv.conf

    - name: Set resolv-file to /etc/upstream-resolv.conf in /etc/dnsmasq.conf
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.conf
        regexp: '^#?resolv-file='
        line: resolv-file=/etc/upstream-resolv.conf
      notify:
        - dnsmasq configuration changed

    - name: Enable expand-hosts in /etc/dnsmasq.conf
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.conf
        regexp: '^#?expand-hosts'
        line: expand-hosts
      notify:
        - dnsmasq configuration changed

    - name: Enable read of additional hosts file in /etc/dnsmasq.conf
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.conf
        regexp: '^#?addn-hosts='
        line: addn-hosts=/etc/addn-hosts
      notify:
        - dnsmasq configuration changed

    - name: Set domain to required value in /etc/dnsmasq.conf
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.conf
        regexp: "^#?domain=(?:thekelleys\\.org\\.uk|{{ home_domain }})"
        line: domain={{ home_domain }}
      notify:
        - dnsmasq configuration changed

    - name: Copy skeleton addn-hosts file
      ansible.builtin.copy:
        content: |
          # Entries for hosts and services
          # BEGIN ANSIBLE MANAGED BLOCK
          # END ANSIBLE MANAGED BLOCK

          # Project entries
        dest: /etc/addn-hosts
        force: no

    - name: Gather IP addresses each DNS host pattern
      ansible.builtin.include_tasks: hosts-matching-pattern.yml
      loop: "{{ dns_host_patterns }}"
      loop_control:
        loop_var: pattern

    - ansible.builtin.template:
        src: addn-hosts.j2
        dest: /tmp/addn-hosts
      vars:
        playbook: >-
          {{
            lookup('file', playbook_dir + '/deploy-host-roles.yml') | from_yaml
          }}

    - name: Template hosts and services lookups to addn-hosts
      ansible.builtin.blockinfile:
        path: /etc/addn-hosts
        block: >-
          {{
            lookup('ansible.builtin.template', './templates/addn-hosts.j2')
          }}
      vars:
        playbook: >-
          {{
            lookup('file', playbook_dir + '/deploy-host-roles.yml') | from_yaml
          }}

  become: yes
  tags: dns
