- name: Deploy the DNS internal role
  become: yes
  block:

    - name: Install APT package(s) required by the DNS internal role
      ansible.builtin.apt:
        install_recommends: no
        update_cache: yes
        name:
          - dnsmasq

    - name: Template out upstream-resolv.conf
      ansible.builtin.template:
        src: upstream-resolv.conf.j2
        dest: /etc/upstream-resolv.conf

    - name: Set resolv-file to /etc/upstream-resolv.conf in /etc/dnsmasq.conf
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.conf
        regexp: '^#?resolv-file='
        line: resolv-file=/etc/upstream-resolv.conf
      notify:
        - dnsmasq configuration changed

    - name: Enable expand-hosts in /etc/dnsmasq.conf
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.conf
        regexp: '^#?expand-hosts'
        line: expand-hosts
      notify:
        - dnsmasq configuration changed

    - name: Enable read of additional hosts file in /etc/dnsmasq.conf
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.conf
        regexp: '^#?addn-hosts='
        line: addn-hosts=/etc/addn-hosts
      notify:
        - dnsmasq configuration changed

    - name: Set domain to required value in /etc/dnsmasq.conf
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.conf
        regexp: "^#?domain=(?:thekelleys\\.org\\.uk|{{ home_domain }})"
        line: domain={{ home_domain }}
      notify:
        - dnsmasq configuration changed

    - name: Template out additional hosts file
      ansible.builtin.template:
        src: addn-hosts.j2
        dest: /etc/addn-hosts
        force: no
      vars:
        # Load the contents of hosts.yml into the variable "playbook"
        playbook: "{{ lookup('file', playbook_dir + '/hosts.yml') | from_yaml }}"
