# ------------------------------------------------------------------------------
# backup_director/handlers/main.yml
# ------------------------------------------------------------------------------

---

# When the backup_director role installs the required APT packages, the
# bacula-director service is not started since at that point we haven't yet
# configured the service with the correct details to access the catalog
# database. When we configure the bacula-director service, we notify that the
# "Bacula director configuration changed" event has happened.

# Note that while systemctl supports relaod of the configuration for the
# bacula-director service, I have observed that following the install this does
# not cause the service to start listening on the configured DIRport. Hence, we
# use the restarted state intead of the reloaded state. Restarted this service
# does not cause any disruption to customers.

- name: Restart the Bacula director service
  ansible.builtin.service:
    name: bacula-director
    state: restarted
  listen: Bacula director configuration changed
  become: yes
