# ------------------------------------------------------------------------------
# mail_external/tasks/configure-domain.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_tasks: configure-domain-handlers.yml

- ansible.builtin.import_tasks: configure-domain-body.yml
