# ------------------------------------------------------------------------------
# mail_external/tasks/configure-domain-handlers.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: mail
    tasks_from: none

- ansible.builtin.import_role:
    name: mta
    tasks_from: none
