# Deploy the email internal role

---

- block:

    # TODO: Make a note somewhere about whether we should have an email server
    # role. In face I probably should have one.
    - name: Import the Dovecot aspects of the email role
      ansible.builtin.import_role:
        name: email
        handlers_from: dovecot
        tasks_from: dovecot

    - name: Install APT package(s) required by the email internal role
      # In addition to the packages installed by the base email role, the
      # internal email server also requires fetchmail to get emails for our home
      # domain from hte external email server.
      ansible.builtin.apt:
        name:
          - fetchmail
        install_recommends: no

    - name: Make fetchmail run in daemon mode
      ansible.builtin.lineinfile:
        path: /etc/default/fetchmail
        regexp: '^START_DAEMON=(?:yes|no)$'
        line: START_DAEMON=yes

    - name: Add the interval option for fetchmail
      ansible.builtin.lineinfile:
        path: /etc/default/fetchmail
        regexp: '^(?:# )?OPTIONS=(?:...|"--daemon 10 --syslog")$'
        line: OPTIONS="--daemon 10 --syslog"

    - name: Deploy fetchmailrc file
      ansible.builtin.template:
        src: fetchmailrc.j2
        dest: /etc/fetchmailrc
        owner: fetchmail
        mode: 0600

    - name: Trust the IMAP connections from clients on the office network
      # Where we have users on clients on the office network we choose to trust
      # this client connections without authentication.
      ansible.builtin.lineinfile:
        path: /etc/dovecot/dovecot.conf
        regexp: '^#?login_trusted_networks ='
        line: login_trusted_networks = {{ office_subnet }}
      notify:
        - dovecot configuration changed

    - name: Copy the Exim localmacros file
      # The Exim localmacros file sets values that tweak our Exim configuration
      # to our exact needs.
      ansible.builtin.copy:
        src: exim-localmacros
        dest: /etc/exim4/exim4.conf.localmacros
      notify:
        - exim configuration changed

    - name: Add REQUIRE_PROTOCOL section to config template
      ansible.builtin.blockinfile:
        path: /etc/exim4/exim4.conf.template
        insertbefore: '^\.ifdef REMOTE_SMTP_HEADERS_REWRITE$'
        block: |-
          .ifdef REQUIRE_PROTOCOL
            protocol = REQUIRE_PROTOCOL
          .endif
      notify:
        - exim configuration changed

  become: yes
