# ------------------------------------------------------------------------------
# backup_storage/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_tasks: install-service.yml

- ansible.builtin.import_tasks: configure-service.yml
