# ------------------------------------------------------------------------------
# monitor_gateway/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: nginx
    handlers_from: service
