---

- block:

    - name: Install APT package(s) required by Dovecot
      ansible.builtin.apt:
        install_recommends: no
        update_cache: yes
        name:
          - dovecot-imapd

    - name: Set Dovecot mail location to Maildir
      ansible.builtin.lineinfile:
        path: /etc/dovecot/conf.d/10-mail.conf
        regexp: '^mail_location = '
        line: mail_location = maildir:~/Maildir

    # TODO: Move creation of the admin user to somewhere generic to all hosts
#    - name: Create accounts for all the office users
#      ansible.builtin.user:
#        name: "{{ item.username }}"
#        password: "{{ item.userpass_encrypted }}"
#      loop: "{{ office_users }}"

  become: yes
