# ------------------------------------------------------------------------------
# wordpress/tasks/delete-site.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_tasks: common/site-vars.yml

- name: Remove site WordPress files
  ansible.builtin.file:
    path: "{{ wordpress_site_path }}"
    state: absent
  become: yes
