# ------------------------------------------------------------------------------
# wordpress/tasks/delete-site.yml
# ------------------------------------------------------------------------------

---

- name: Remove site WordPress files
  ansible.builtin.file:
    path: "/var/www/{{ wordpress_site_server_name }}"
    state: absent
  become: yes
