# ------------------------------------------------------------------------------
# wordpress/tasks/dependencies.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: mta
