# ------------------------------------------------------------------------------
# wordpress/tasks/subdomains
# ------------------------------------------------------------------------------

# This task list determines the subdomains that tasks that affect with WordPress
# sites should act upon - see:
# https://github.com/varilink/libraries-ansible#controlling-the-wordpress-sites-impacted-by-project-playbooks

---

- name: >-
    Check that either playbook_subdomains or run_subdomains or both is defined
  ansible.builtin.fail:
    msg: >-
      Neither playbook_subdomains nor run_subdomains is defined - see
      https://github.com/varilink/libraries-ansible#controlling-the-wordpress-sites-impacted-by-project-playbooks
  run_once: true
  when: playbook_subdomains is not defined and run_subdomains is not defined

- name: >-
    Determine the subdomains that are in scope within the current task context
  ansible.builtin.set_fact:
    subdomains: |-
      {% if subdomains_filter is defined %}
        {{- subdomains_scope | intersect(subdomains_configured) |
            intersect(subdomains_filter) }}
      {%- else %}
        {{- subdomains_scope | intersect(subdomains_configured) }}
      {%- endif %}
  vars:
    # The subdomains in the scope of the current playbook run.
    subdomains_scope: |-
      {% if playbook_subdomains is defined %}
        {%- if run_subdomains is defined %}
          {{- playbook_subdomains | intersect(run_subdomains.split(',')) }}
        {%- else %}
          {{- playbook_subdomains }}
        {%- endif %}
      {%- else %}
        {{- run_subdomains.split(',')}}
      {%- endif %}
    # The subdomains configured via the inventory in the current task context.
    subdomains_configured: "\
      {{ wp_sites | map(attribute='subdomain') }}"
