- name: >-
    Set facts from the elements of the wordpress_sites array for the current
    subdomain
  ansible.builtin.set_fact: "wordpress_site_{{ item.key }}={{ item.value }}"
  loop: >-
    {{
      wordpress_sites | selectattr('subdomain', 'equalto', subdomain) |
      first | dict2items
    }}
  when: wordpress_sites_private is not defined

- name: >-
    Set facts from combining the elements from the wordpress_sites and
    wordpress_sites_private variables for the current subdomain
  ansible.builtin.set_fact: "wordpress_site_{{ item.key }}={{ item.value }}"
  loop: >-
    {{
      wordpress_sites | selectattr('subdomain', 'equalto', subdomain) |
      first | dict2items |
      union(
      wordpress_sites_private | selectattr('subdomain', 'equalto', subdomain) |
      first | dict2items)
    }}
  when: wordpress_sites_private is defined

- name: Set the wordpress_site_server_name fact 
  ansible.builtin.set_fact:
    wordpress_site_server_name: "\
      {{ wordpress_site_subdomain }}.{{ domain_name }}"

- name: Set the wordpress_site_path fact
  ansible.builtin.set_fact:
    wordpress_site_path: /var/www/{{ wordpress_site_server_name }}/html
