- block:

    - ansible.builtin.import_tasks: initialize-site/plugins.yml
      when: wordpress_site_plugins is defined

    - ansible.builtin.import_tasks: initialize-site/themes.yml
      when: wordpress_site_themes is defined

    - ansible.builtin.import_tasks: initialize-site/sidebars.yml
      when: wordpress_site_sidebars is defined

  become: yes
  become_user: www-data