# ------------------------------------------------------------------------------
# wordpress/tasks/install-service.yml
# ------------------------------------------------------------------------------

---

- block:

    - name: Install common APT package(s) for the wordpress host role
      ansible.builtin.apt:
        name:
          - acl
          - ca-certificates
          - jq
          - less
          - php
          - php-mysql
          - rsync
          - unzip
        install_recommends: no

    - name: Install WP-CLI
      ansible.builtin.get_url:
        url: "https://\
          raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
        dest: /usr/local/sbin/wp
        mode: '755'

    - name: Make the .wp-cli folder for WP-CLI
      ansible.builtin.file:
        path: /var/www/.wp-cli
        state: directory
        owner: www-data
        group: www-data

    - name: Install the WP-CLI find command's package
      ansible.builtin.command:
        cmd: wp package install wp-cli/find-command
        creates: ~/.wp-cli/packages/vendor/wp-cli/find-command
      become_user: www-data

  become: yes
