# ------------------------------------------------------------------------------
# wordpress/tasks/install-service.yml
# ------------------------------------------------------------------------------

---

- block:

    - name: Install common APT package(s) for the wordpress host role
      ansible.builtin.apt:
        name:
          - acl
          - ca-certificates
          - gosu
          - jq
          - less
          - php
          - php-gd
          - php-imagick
          - php-mysql
          - php-xml
          - php-zip
          - rsync
          - unzip
        install_recommends: no
      # When the PHP packages are installed, the Apache2 configuration must be
      # reloaded for Apache2 to recognise their presence.
      notify: Apache2 configuration changed

    - name: Install WP-CLI
      ansible.builtin.get_url:
        url: "https://\
          raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
        dest: /usr/local/sbin/wp
        mode: '755'

    - name: >-
        Create the .wp-cli and .ansible directories within /var/www for the
        www-data user
      ansible.builtin.file:
        path: /var/www/{{ item }}
        state: directory
        owner: www-data
        group: www-data
      loop: [ '.ansible', '.wp-cli' ]

    - name: Configure WP-CLI to be able to hard flush rewrite rules
      ansible.builtin.copy:
        dest: /var/www/.wp-cli/config.yml
        content: |
          apache_modules:
            - mod_rewrite
        owner: www-data
        group: www-data

    - name: "\
        Create the tmp directory within /var/www/.ansible for the www-data user"
      ansible.builtin.file:
        path: /var/www/.ansible/tmp
        state: directory
        owner: www-data
        group: www-data
        mode: u=rwx,g=,o=

    - name: Install the WP-CLI find command's package
      ansible.builtin.command:
        cmd: wp package install wp-cli/find-command
        creates: ~/.wp-cli/packages/vendor/wp-cli/find-command
      become_user: www-data

  become: yes
