---

- block:

    - name: Install common apt package(s) for the wordpress host role
      ansible.builtin.apt:
        install_recommends: no
        update_cache: yes
        name:
          - ca-certificates
          - jq
          - php
          - php-mysql
          - unzip

    - name: Install WP-CLI
      ansible.builtin.get_url:
        url: "https://\
          raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
        dest: /usr/local/sbin/wp
        mode: '755'

    - name: Install the WP-CLI find command's package
      ansible.builtin.command:
        cmd: wp --allow-root package install wp-cli/find-command
        creates: ~/.wp-cli/packages/vendor/wp-cli/find-command

  become: yes
