# Main install tasks for the WordPress role.

---

- name: Deploy wordpress host role
  become: yes
  block:

    - name: Install apt package(s) for wordpress host role
      ansible.builtin.apt:
        install_recommends: no
        update_cache: yes
        name:
          - apache2
          - ca-certificates
          - libapache2-mod-php
          - jq
          - php
          - php-mysql
          - unzip

    - name: Enable apache2 rewrite module
      community.general.apache2_module:
        state: present
        name: rewrite

    # TODO: Check if task is necessary
    # This directory isn't present on multiple Apache webservers that I have
    # in current use so I wonder if perhaps it isn't needed.
    #- name: Create apache2 run directory
    #  file:
    #    path: /var/run/apache2
    #    state: directory

    - name: Change ports that apache2 will listen on
      ansible.builtin.template:
        src: ports.conf.j2
        dest: /etc/apache2/ports.conf
        mode: '755'

    - name: Install WP-CLI
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp
        mode: '755'

    - name: Install the WP-CLI find command's package
      ansible.builtin.command:
        cmd: wp --allow-root package install wp-cli/find-command
        creates: ~/.wp-cli/packages/vendor/wp-cli/find-command

    - name: Install WordPress backup script
      ansible.builtin.template:
        src: wordpress-backup.sh.j2
        dest: /etc/bacula/scripts/wordpress-backup.sh
        mode: 0644
