# site_wordpress/tasks/restore.yml

---

- block:

    # NOTE: This tasks runs for a few minutes and doesn't start generating
    # output on the target until a good way through that time. Be patient.
    - name: Restore files from backup
      ansible.builtin.unarchive:
        src: >-
          {{ lookup('ansible.builtin.fileglob',
            playbook_dir + '/backup/' + (
              source_wp_server_name | regex_replace ('\.', '_')
              ) + '*.tar.gz'
          ) }}
        dest: "/var/www/{{ wp_server_name }}/html"
        include: wp-content/uploads
        group: www-data
        owner: www-data

    - name: Restore database from backup
      ansible.builtin.command:
        cmd: >-
          wp --allow-root
          --path=/var/www/{{ wp_server_name }}/html
          db import -
        # Use the contents of the database export that "with_fileglob" found as
        # stdin for the cmd.
        stdin: "{{ lookup('file', item) }}"
        # Find the single .sql file within the backup folder that will contain a
        # recent database export.
      with_fileglob:
        - >-
          {{
            playbook_dir + '/backup/' + (
              source_wp_server_name | regex_replace ('\.', '_')
            ) + '*.sql'
          }}

    - name: Search and replace the source server name if it is different
      ansible.builtin.command:
        cmd: >-
          wp --allow-root
          --path=/var/www/{{ wp_server_name }}/html
          search-replace
          {{ source_wp_server_name }}
          {{ wp_server_name }}
      when: source_wp_server_name != wp_server_name

    - debug:
        var: wp_admin_user

    - debug:
        var: wp_admin_password

    - debug:
        var: wp_server_name

    - name: Set the admin user's password for this environment
      ansible.builtin.command:
        cmd: >-
          wp --allow-root
          --path=/var/www/{{ wp_server_name }}/html
          user update {{ wp_admin_user }}
          --user_pass='{{ wp_admin_password }}'
      register: user_update

    - debug:
        var: user_update

  become: yes
