- name: Generate a Dovecot password hash for the user
  ansible.builtin.command: >-
    doveadm pw
    -s CRYPT
    -p {{ user.passwd }}
    -u {{ user.email }}@{{ domain_name }}
  register: pw_hash

- name: Add virtual mail user
  ansible.builtin.lineinfile:
    path: /etc/dovecot/users
    line: "\
      {{ user.email }}@{{ domain_name }}:\
      {{ pw_hash.stdout }}::::\
      /home/vmail/{{ user.email }}@{{ domain_name }}::\
      "
    regexp: "^{{ ( user.email + '@' + domain_name + ':' ) | regex_escape() }}"

- name: Create folder for the user's mailbox
  ansible.builtin.file:
    path: /home/vmail/{{ user.email }}@{{ domain_name }}
    state: directory
    owner: vmail
    group: vmail
