# ------------------------------------------------------------------------------
# monitor_server/tasks/install-service.yml
# ------------------------------------------------------------------------------

---

- name: Install APT packages required by the monitor_server role
  ansible.builtin.apt:
    name:
      - acl
      - ca-certificates
      - gosu
      - gpg
      - python3-cryptography
    install_recommends: no
  become: yes

- ansible.builtin.import_role:
    name: influxdata

- name: Install InfluxDB APT packages
  ansible.builtin.apt:
    name:
      - influxdb2
      - influxdb2-cli
    install_recommends: no
  become: yes
