# ------------------------------------------------------------------------------
# monitor_server/tasks/install-service.yml
# ------------------------------------------------------------------------------

---

- name: Install APT packages required by the monitor_server role
  ansible.builtin.apt:
    name:
      - acl
      - ca-certificates
      - gosu
      - gpg
    install_recommends: no
  become: yes

- ansible.builtin.import_role:
    name: influxdata

- block:

    - name: Install InfluxDB APT packages
      ansible.builtin.apt:
        name:
          - influxdb2
          - influxdb2-cli
        install_recommends: no

    - name: Start the influxd service
      ansible.builtin.service:
        name: influxdb
        state: started

  become: yes
