---

- name: Reload Bacula storage daemon configuration
  ansible.builtin.service:
    name: bacula-sd
    state: reloaded
  listen: Bacula storage daemon configuration changed
  become: yes

- debug:
    msg: If you are seeing this message then something has gone wrong
  listen: Bacula storage daemon installed
  when: false
