# ------------------------------------------------------------------------------
# database/tasks/site/delete.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.set_fact: "wordpress_site_{{ item.key }}={{ item.value }}"
  loop: >-
    {{
      wordpress_sites | selectattr('subdomain', 'equalto', subdomain) |
      first | dict2items |
      union(
      wordpress_sites_private | selectattr('subdomain', 'equalto', subdomain) |
      first | dict2items)
    }}

- block:

    - name: Drop a local database user for the WordPress site
      community.mysql.mysql_user:
        name: "{{ wordpress_site_server_name | regex_replace ('\\.', '_') }}"
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock
      when: wordpress_site_database_host is not defined

    - name: Drop a remote database user for the WordPress site
      community.mysql.mysql_user:
        name: "{{ wordpress_site_server_name | regex_replace ('\\.', '_') }}"
        host: "{{ wordpress_site_database_host }}"
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock
      when: wordpress_site_database_host is defined

    - name: Drop database for the WordPress site
      community.mysql.mysql_db:
        name: "{{ wordpress_site_server_name | regex_replace ('\\.', '_') }}"
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock

  become: yes
  vars:
    wordpress_site_server_name: "\
      {{ wordpress_site_subdomain }}.{{ domain_name }}"
