
---

- name: Check if domain wordpress is needed for this host
  ansible.builtin.include_tasks: create.yml
  when: >-
    (
      hostname_filter is not defined
      or webhost.name is regex(hostname_filter)
    )
    and inventory_hostname == webhost.wordpress_host
  loop: "{{ domain.webhosts }}"
  loop_control:
    loop_var: webhost
