- block:

    - name: Activate the restricted-site-access plugin if required
      # NOTE: Reports changed even if plugin already activated.
      # TODO: Try to make it skip if plugin already activated.
      ansible.builtin.command: >-
        wp --allow-root
        --path=/var/www/{{ wordpress_site_server_name }}/html
        plugin install restricted-site-access --activate

    - name: Deactivate the google-captcha plugin
      ansible.builtin.command: >-
        wp --allow-root
        --path=/var/www/{{ wordpress_site_server_name }}/html
        plugin deactivate google-captcha
      # NOTE: Fails if the plugin is not present. This is a workaround for now.
      # TODO: Only run this task if the plugin is installed and activated.
      ignore_errors: yes

    - name: Remove reCAPTCHA integration from Contact 7 plugin
      ansible.builtin.command: >-
        wp --allow-root
        --path=/var/www/{{ wordpress_site_server_name }}/html
        option patch delete wpcf7 recaptcha
      # NOTE: Fails if the plugin is not present with this option configured.
      # TODO: Only run this task if the plugin is installed and activated and
      # with reCAPTHCHA integration configured.
      ignore_errors: yes

  become: yes
