- block:

  - name: Determine the status of the dnsmasq service
    ansible.builtin.service_facts:
    listen: dnsmasq configuration changed

  - name: Reload the dnsmasq configuration if the service is running
    ansible.builtin.service:
      name: dnsmasq
      state: reloaded
    when: ansible_facts['services']['dnsmasq']['state'] == 'running'
    listen: dnsmasq configuration changed
    

  become: yes
