# ------------------------------------------------------------------------------
# wordpress_apache/tasks/configure-service.yml
# ------------------------------------------------------------------------------

---

- name: Get the codename of the Debian release on this host
  ansible.builtin.command: lsb_release --codename --short
  register: lsb_release
  changed_when: false

- block:

    - name: Disable the default Apache site
      ansible.builtin.file:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: absent
      notify: Apache2 configuration changed

    - name: Listening on port 8080 on the local interface using http protocol
      ansible.builtin.lineinfile:
        path: /etc/apache2/ports.conf
        line: 'Listen 127.0.0.1:8080 http'
        regexp: '^Listen (?:127\.0\.0\.1:)?(?:80|8080)(?: http)?$'
      notify: Apache2 configuration changed

    - name: Disable apache2 mpm_event module
      community.general.apache2_module:
        name: mpm_event
        state: absent
        ignore_configcheck: yes
      notify: Apache2 configuration changed

    - community.general.apache2_module:
        name: mpm_prefork
        state: present
        ignore_configcheck: yes
      notify: Apache2 configuration changed

    - name: Enable apache2 rewrite and php modules
      community.general.apache2_module:
        name: "{{ item }}"
        state: present
      notify: Apache2 configuration changed
      loop:
        - rewrite
        - |-
            {% if lsb_release.stdout == 'bullseye' %}
            php7.4
            {%- elif lsb_release.stdout == 'buster' %}
            php7.3
            {%- endif %}

    # Any host for the wordpress_apache role must also host the backup_client
    # role. However, the playbook that applies these roles to the host may apply
    # the backup_client role after the wordpress_apache role, in which case the
    # /etc/bacula/scripts directory will not yet be in place.
    - name: Ensure that the /etc/bacula/scripts directory is present
      ansible.builtin.file:
        path: /etc/bacula/scripts
        state: directory

    - name: Install WordPress backup script
      ansible.builtin.copy:
        src: wordpress-apache-backup.sh
        dest: /etc/bacula/scripts/wordpress-apache-backup.sh
        mode: 0644

  become: yes
