# ------------------------------------------------------------------------------
# wordpress_apache/tasks/create-site.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: wordpress
    tasks_from: create-site.yml

- block:

  - name: Make site apache2 configuration available
    ansible.builtin.template:
      src: apache2.conf.j2
      dest: /etc/apache2/sites-available/{{ wordpress_site_server_name }}.conf
    notify:
      - Apache2 configuration changed

  - name: Enable site apache2 configuration
    ansible.builtin.file:
      src: /etc/apache2/sites-available/{{ wordpress_site_server_name }}.conf
      dest: /etc/apache2/sites-enabled/{{ wordpress_site_server_name }}.conf
      state: link
    notify:
      - Apache2 configuration changed

  - name: Listen on WordPress site's custom port on local interface only
    ansible.builtin.lineinfile:
      path: /etc/apache2/ports.conf
      line: Listen 127.0.0.1:{{ wordpress_site_reverse_proxy_pass_port }} http
      insertafter: 'Listen 127.0.0.1:8080 http'
    notify:
      - Apache2 configuration changed
    # We do not expose Apache WordPress sites externally on this host at a
    # host level and this is not countermanded for this WordPress site.
    when: >-
      not wordpress_expose_externally and (
        wordpress_site_expose_externally is not defined
        or not wordpress_site_expose_externally
      )

  - name: Listen on WordPress site's custom port on all interfaces
    ansible.builtin.lineinfile:
      path: /etc/apache2/ports.conf
      line: Listen {{ wordpress_site_reverse_proxy_pass_port }} http
      regexp: >-
        ^Listen
        (?:127\.0\.0\.1:)?{{
          wordpress_site_reverse_proxy_pass_port
        }}$'
      insertafter: '# Custom site Listen entries'
    # We expose Apache WordPress sites externally on this host at a host level
    # and this is not countermanded for this WordPress site.
    notify:
      - Apache2 configuration changed
    when: >-
      wordpress_expose_externally and (
        wordpress_site_expose_externally is not defined
        or wordpress_site_expose_externally
      )

  become: yes
