# ------------------------------------------------------------------------------
# wordpress_apache/tasks/create-site-stack.yml
# ------------------------------------------------------------------------------

- name: Check for a single host
  fail: msg="Single host check failed"
  when: (play_hosts|length) != 1

- block:

    - name: Install WordPress site's database
      ansible.builtin.import_role:
        name: database
        tasks_from: create-site.yml

    - name: Install WordPress site's reverse proxy
      ansible.builtin.import_role:
        name: reverse_proxy
        tasks_from: create-site.yml

    - ansible.builtin.import_tasks: create-site.yml

    - ansible.builtin.import_tasks: enable-ssl.yml

  vars:
    wordpress_site_server_name: "\
      {{ wordpress_site_subdomain }}.{{ domain_name }}"
    wordpress_site_path: "/var/www/{{ wordpress_site_server_name }}/html"
