- ansible.builtin.import_role:
    name: wordpress
    tasks_from: get-site-vars

- ansible.builtin.import_role:
    name: database
    tasks_from: create-site
    handlers_from: none
  delegate_to: "\
    {{ wordpress_site_database_host | default(inventory_hostname) }}"

- ansible.builtin.import_role:
    name: wordpress
    tasks_from: create-site

- ansible.builtin.import_tasks: create-site-apache.yml

- ansible.builtin.import_role:
    name: reverse_proxy
    tasks_from: create-site
  delegate_to: "\
    {{ wordpress_site_reverse_proxy_host | default(inventory_hostname) }}"

- ansible.builtin.import_role:
    name: dns
    tasks_from: create-project-record
  vars:
    dns_record_hostname: "{{ wordpress_site_server_name }}"
  delegate_to: "\
    {{ wordpress_site_dns_host | default(inventory_hostname) }}"
