# ------------------------------------------------------------------------------
# wordpress_apache/tasks/site/create.yml
# ------------------------------------------------------------------------------

---

- block:

    - name: Insert block markers for the "behind proxy" block
      ansible.builtin.lineinfile:
        path: "{{ wp_path }}/wp-config.php"
        line: "{{ item }}"
        insertbefore: "^# END EXTRA PHP"
      loop:
        - "# BEGIN ANSIBLE MANAGED BEHIND PROXY BLOCK"
        - "# END ANSIBLE MANAGED BEHIND PROXY BLOCK"

    - name: Add to WordPress config to cater for being behind a proxy
      ansible.builtin.blockinfile:
        path: "{{ wp_path }}/wp-config.php"
        marker: "# {mark} ANSIBLE MANAGED BEHIND PROXY BLOCK"
        block: |-
          {% if wp_uses_ssl %}
          $_SERVER['HTTPS']='on';
          {% endif %}
          if ( array_key_exists('HTTP_X_REAL_IP', $_SERVER) ) {
            $_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_X_REAL_IP']; 
          }

    - name: Make site apache2 configuration available
      ansible.builtin.template:
        src: apache2.conf.j2
        dest: /etc/apache2/sites-available/{{ wp_server_name }}.conf
      notify:
        - Apache2 configuration changed

    - name: Enable site apache2 configuration
      ansible.builtin.file:
        src: /etc/apache2/sites-available/{{ wp_server_name }}.conf
        dest: /etc/apache2/sites-enabled/{{ wp_server_name }}.conf
        state: link
      notify:
        - Apache2 configuration changed

    - name: Listen on WordPress site's custom port on local interface only
      ansible.builtin.lineinfile:
        path: /etc/apache2/ports.conf
        line: Listen 127.0.0.1:{{ wp_reverse_proxy_pass_port }} http
        regexp: "\
          ^Listen (?:127\\.0\\.0\\.1:)?{{ wp_reverse_proxy_pass_port }} http$"
        insertafter: 'Listen 127.0.0.1:8080 http'
      notify:
        - Apache2 configuration changed
      # We do not expose this Apache WordPress site externally
      when: not wp_expose_externally

    - name: Listen on WordPress site's custom port on all interfaces
      ansible.builtin.lineinfile:
        path: /etc/apache2/ports.conf
        line: Listen {{ wp_reverse_proxy_pass_port }} http
        regexp: "\
          ^Listen (?:127\\.0\\.0\\.1:)?{{ wp_reverse_proxy_pass_port }} http$"
        insertafter: '# Custom site Listen entries'
      notify:
        - Apache2 configuration changed
      # We expose this Apache WordPress site externally
      when: wp_expose_externally

  become: yes
