# ------------------------------------------------------------------------------
# wordpress_apache/tasks/create-sites.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: wordpress
    tasks_from: get-subdomains

- ansible.builtin.include_tasks: create-site.yml
  vars:
    site_dns_host: "{{ wp_dns_host }}"
    site_host: "{{ wp_reverse_proxy_host }}"
    site_server_name: "{{ wp_server_name }}"
  loop: "{{ subdomains }}"
  loop_control:
    loop_var: subdomain
