# ------------------------------------------------------------------------------
# wordpress_apache/tasks/site/delete.yml
# ------------------------------------------------------------------------------

---

- name: Include either service or process Apache2 handlers as appropriate
  ansible.builtin.include_role:
    name: wordpress_apache
    tasks_from: none
    handlers_from: "{{ handlers_from }}"

- ansible.builtin.import_role:
    name: wordpress
    tasks_from: get-site-vars

- ansible.builtin.import_role:
    name: dns
    tasks_from: delete-project-record
  vars:
    dns_record_hostname: "{{ wordpress_site_server_name }}"
  delegate_to: "\
    {{ wordpress_site_dns_host | default(inventory_hostname) }}"
  when: "'internal' in group_names"

- ansible.builtin.import_role:
    name: reverse_proxy
    tasks_from: delete-site
  delegate_to: "\
    {{ wordpress_site_reverse_proxy_host | default(inventory_hostname) }}"

- block:

    - name: "\
        Stop listening on WordPress site's custom port on local interface only"
      ansible.builtin.lineinfile:
        path: /etc/apache2/ports.conf
        line: Listen 127.0.0.1:{{ wordpress_site_reverse_proxy_pass_port }} http
        state: absent
      notify:
        - Apache2 configuration changed
      when: >-
        not wordpress_expose_externally and (
          wordpress_site_expose_externally is not defined
          or not wordpress_site_expose_externally
        )

    - name: Stop listening on WordPress site's custom port on all interfaces
      ansible.builtin.lineinfile:
        path: /etc/apache2/ports.conf
        line: Listen {{ wordpress_site_reverse_proxy_pass_port }} http
        state: absent
      notify:
        - Apache2 configuration changed
      when: >-
        wordpress_expose_externally and (
          wordpress_site_expose_externally is not defined
          or wordpress_site_expose_externally
        )

    - name: Disable site apache2 configuration
      ansible.builtin.file:
        path: /etc/apache2/sites-enabled/{{ wordpress_site_server_name }}.conf
        state: absent
      notify:
        - Apache2 configuration changed

    - name: Make site apache2 configuration unavailable
      ansible.builtin.file:
        path: /etc/apache2/sites-available/{{ wordpress_site_server_name }}.conf
        state: absent
      notify:
        - Apache2 configuration changed

  become: yes

- ansible.builtin.import_role:
    name: wordpress
    tasks_from: delete-site

- ansible.builtin.import_role:
    name: database
    tasks_from: delete-site
  delegate_to: "\
    {{ wordpress_site_database_host | default(inventory_hostname) }}"
