# ------------------------------------------------------------------------------
# wordpress_apache/tasks/delete-sites.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: wordpress
    tasks_from: get-subdomains

- ansible.builtin.include_tasks: site/delete.yml
  loop: "{{ subdomains }}"
  loop_control:
    loop_var: subdomain
