# ------------------------------------------------------------------------------
# wordpress_apache/tasks/site/delete.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: wordpress
    tasks_from: get-site-vars

- ansible.builtin.import_role:
    name: dns
    tasks_from: delete-project-record
  vars:
    dns_record_hostname: "{{ wp_server_name }}"
  delegate_to: "{{ wp_dns_host | default(inventory_hostname) }}"
  when: "'internal' in group_names"

- ansible.builtin.import_role:
    name: reverse_proxy
    tasks_from: delete-site
  delegate_to: "{{ wp_reverse_proxy_host | default(inventory_hostname) }}"

- block:

    - name: "\
        Stop listening on WordPress site's custom port on local interface only"
      ansible.builtin.lineinfile:
        path: /etc/apache2/ports.conf
        line: Listen 127.0.0.1:{{ wp_reverse_proxy_pass_port }} http
        state: absent
      notify:
        - Apache2 configuration changed
      when: >-
        not wp_expose_externally and (
          wp_expose_site_externally is not defined
          or not wp_expose_site_externally
        )

    - name: Stop listening on WordPress site's custom port on all interfaces
      ansible.builtin.lineinfile:
        path: /etc/apache2/ports.conf
        line: Listen {{ wp_reverse_proxy_pass_port }} http
        state: absent
      notify:
        - Apache2 configuration changed
      when: >-
        wp_expose_externally and (
          wp_expose_site_externally is not defined
          or wp_expose_site_externally
        )

    - name: Disable site apache2 configuration
      ansible.builtin.file:
        path: /etc/apache2/sites-enabled/{{ wp_server_name }}.conf
        state: absent
      notify:
        - Apache2 configuration changed

    - name: Make site apache2 configuration unavailable
      ansible.builtin.file:
        path: /etc/apache2/sites-available/{{ wp_server_name }}.conf
        state: absent
      notify:
        - Apache2 configuration changed

  become: yes

- ansible.builtin.import_role:
    name: wordpress
    tasks_from: delete-site

- ansible.builtin.import_role:
    name: database
    tasks_from: delete-site
  delegate_to: "{{ wp_database_host | default(inventory_hostname) }}"
