---

- block:

    - name: Install apt package(s) for wordpress host role using Apache
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        install_recommends: no
        update_cache: yes

    - name: Enable apache2 rewrite module
      community.general.apache2_module:
        name: rewrite
        state: present
      notify: apache2 configuration changed

    - name: Install WordPress backup script
      ansible.builtin.copy:
        src: wordpress-apache-backup.sh
        dest: /etc/bacula/scripts/wordpress-apache-backup.sh
        mode: 0644

  become: yes
