# ------------------------------------------------------------------------------
# wordpress_apache/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_tasks: dependencies.yml

- ansible.builtin.import_tasks: install.yml

- ansible.builtin.import_tasks: configure.yml
