---

- block:

    - name: Install apt package(s) for wordpress host role using Apache
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        install_recommends: no
        update_cache: yes

    - name: Disable the default Apache site
      ansible.builtin.file:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: absent
      notify: apache2 configuration changed

    # I always use Apache behind and Nginx proxy. The Nginx proxy listens on
    # port 80, and if HTTPS is supported, also on port 443. Apache listens on
    # custom ports, one per site, and supports HTTP only.
    - name: Stop Apache listening on port 80
      ansible.builtin.lineinfile:
        path: /etc/apache2/ports.conf
        line: "# Custom site Listen entries"
        regexp: '^Listen 80|# Custom site Listen entries$'
      notify: apache2 configuration changed

    - name: Enable apache2 rewrite module
      community.general.apache2_module:
        name: rewrite
        state: present
      notify: apache2 configuration changed

    - name: Install WordPress backup script
      ansible.builtin.copy:
        src: wordpress-apache-backup.sh
        dest: /etc/bacula/scripts/wordpress-apache-backup.sh
        mode: 0644

  become: yes
