# ------------------------------------------------------------------------------
# dns_client/tasks/main.yml
# ------------------------------------------------------------------------------

---

- name: Template out resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    unsafe_writes: "{{ unsafe_writes }}"
  become: yes
