- block:

    - name: Template site nginx configuration to sites-available
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ wordpress_site_server_name }}
      notify:
        - nginx configuration changed

    - name: Enable site nginx configuration
      ansible.builtin.file:
        src: /etc/nginx/sites-available/{{ wordpress_site_server_name }}
        dest: /etc/nginx/sites-enabled/{{ wordpress_site_server_name }}
        state: link
      notify:
        - nginx configuration changed

  vars:
    wordpress_site_server_name: "\
      {{ wordpress_site.subdomain }}.{{ domain_name }}"
  become: yes
