# ------------------------------------------------------------------------------
# reverse_proxy/tasks/create-site-body.yml
# ------------------------------------------------------------------------------

# The tasks that create a site on a reverse proxy. See also the create-site.yml
# task list within this same role.

---

- name: "\
    Fail if WordPress site uses SSL but reverse proxy does not support SSL"
  # A reverse proxy host can be configured to support SSL or not, as indicated
  # by the host_enabled_for_ssl variable, if it is defined. If it isn't defined
  # then the host is configured to support SSL by default. Similarly, a
  # WordPress site can be configured to use SSL or not, as indicated by the
  # wp_uses_ssl variable, if it is defined. Again, if it isn't defined then the
  # wordpress site uses SSL by default. If a WordPress site is configured to use
  # SSL via a reverse proxy host that is not configured to support SSL, then
  # fail.
  ansible.builtin.fail:
    msg: >-
      Invalid request to install a WordPress site that uses SSL via a
      reverse proxy that does not support SSL
  # If wp_reverse_proxy_host is defined then this task has been delegated to
  # another host and so we must determine if that host is enabled for SSL. If
  # wp_reverse_proxy_host isn't defined then we must check the current host.
  when: >-
    wp_uses_ssl
    and (
      (
        wp_reverse_proxy_host is defined and
        hostvars[wp_reverse_proxy_host].host_enabled_for_ssl is defined and
        not hostvars[wp_reverse_proxy_host].host_enabled_for_ssl
      )
      or (
        wp_reverse_proxy_host is not defined and
        host_enabled_for_ssl is defined and
        not host_enabled_for_ssl
      )
    )

- block:

    - name: Generate self-signed certificate if it isn't already installed
      ansible.builtin.command:
        cmd: >-
          openssl req -new -x509 -nodes -days 1095
          -out /etc/ssl/certs/{{ wp_server_name | replace('.', '_') }}.pem
          -keyout /etc/ssl/private/{{ wp_server_name | replace('.', '_') }}.pem
          -subj '/CN={{ wp_server_name }}'
          {% if wp_subdomain == 'www' %}
          -addext "subjectAltName = DNS:{{ domain_name }}"
          {%- endif %}
        creates: >-
          /etc/ssl/certs/{{
          wp_server_name | replace('.', '_')
          }}.pem
      # The WordPress site is SSL enabled using a self-signed certificate, so we
      # must generate that certificate if it doesn't exist already.
      when: wp_uses_ssl and not wp_uses_ca

    - name: >-
        Determine if a certification authority's certificate is installed
      ansible.builtin.shell: "\
        certbot certificates | grep 'Certificate Name: {{ wp_server_name }}'"
      register: certbot_certificates
      failed_when: certbot_certificates.rc != 0 and certbot_certificates.rc != 1
      changed_when: false
      # The WordPress site is SSL enabled using a CA certificate, so see if we
      # already have one installed.
      when: wp_uses_ssl and wp_uses_ca

    - name: Template site Nginx configuration to sites-available
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ wp_server_name }}.conf
      notify: Nginx configuration changed
      vars:
        certbot_certificate_installed_string: |-
          {%
            if certbot_certificates.rc is defined and
            certbot_certificates.rc == 0
          %}
          yes
          {%- else %}
          no
          {%- endif %}
        certbot_certificate_installed: "\
          {{ certbot_certificate_installed_string | bool }}"
              
    - name: Enable site nginx configuration
      ansible.builtin.file:
        src: /etc/nginx/sites-available/{{ wp_server_name }}.conf
        dest: /etc/nginx/sites-enabled/{{ wp_server_name }}.conf
        state: link
      notify: Nginx configuration changed

    # Flush handlers so that if the site is newly configured it becomes
    # available immediately for the Let's Encrypt HTTP-01 challenge if we're
    # going to go on and install a Let's Encrypt certificate. Note that we can't
    # place flush_handlers within a when conditional.
    - meta: flush_handlers

    - block:

        # A certification authority's certificate is not yet installed, so get
        # and install one.

        - name: Install certbot certificate
          ansible.builtin.command: >-
            certbot -n certonly
            --webroot -w {{ wp_path }} -d {{ wp_server_name }}
            {% if wp_subdomain == 'www' -%}
            -d {{ domain_name }}
            {%- endif %}

        - name: Template site nginx configuration to sites-available
          ansible.builtin.template:
            src: nginx.conf.j2
            dest: /etc/nginx/sites-available/{{ wp_server_name }}.conf
          notify: Nginx configuration changed
          vars:
            certbot_certificate_installed: yes

      become: yes
      when: >-
        wp_uses_ssl and wp_uses_ca and certbot_certificates.rc == 1

  become: yes
