# ------------------------------------------------------------------------------
# reverse_proxy/tasks/install.yml
# ------------------------------------------------------------------------------

---

- name: Install APT package(s) for reverse proxy role
  ansible.builtin.apt:
    name: nginx
    install_recommends: no
  become: yes
