# ------------------------------------------------------------------------------
# reverse_proxy/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: nginx
