# ------------------------------------------------------------------------------
# dynamic_dns/tasks/copy-project-records.yml
# ------------------------------------------------------------------------------

---

#-------------------------------------------------------------------------------
# Deploys the configuration files for a project that uses the dynamic DNS
# service. Each A record that must be kept in line with our ISP allocated IP
# address is configured as a separate YAML file that contains the Linode Id for
# both the domain and for the associated record.
#-------------------------------------------------------------------------------

- name: Write the project's configuration file(s) for dynamic DNS A records
  ansible.builtin.copy:
    # Name the configuration file using the FQDN for the A record that is to be
    # kept updated; for example test.varilink.co.uk.yml.
    dest: "{{ dynamic_dns_records_dir }}/{{ item.key }}.{{ domain_name }}.yml"
    content: |
      domain: {{ domain_linode_id }}
      record: {{ item.value }}
  loop: "{{ domain_linode_dynamic_dns_records | dict2items }}"
  become: yes
