# dynamic_dns/tasks/main.yml

---

#-------------------------------------------------------------------------------
# Deploy to base dynamic DNS capability. Dynamic DNS services on a per domain
# basis can then be configured on this service using domain.yml tasks list in
# this role.
#-------------------------------------------------------------------------------

- block:

    # Import the dns_api role to provide the configuration for access the Linode
    # API service to manipulate DNS records. This is also required by the
    # mail_certificates role and so is implemented in a separate role to enable
    # that sharing. We use an import_role task rather than a meta dependency so
    # that the domain.yml tasks can be invoked without pulling the dns_api role
    # in again.
    - ansible.builtin.import_role:
        name: dns_api

    - name: Install APT packages used by the dynamic DNS role
      ansible.builtin.apt:
        name:
          - cron
          - libconfig-tiny-perl
          - libjson-perl
          - libperl5.32
          - libwww-perl
          - libyaml-perl
          # Ensure that an editor is present in case we want to `crontab -e` if
          # only to conveniently inspect the crontab.
          - nano
        install_recommends: no

    - name: Deploy the dynamic-dns script
      ansible.builtin.template:
        src: dynamic-dns.pl.j2
        dest: /usr/local/src/dynamic-dns.pl
        mode: 0644

    # We may have changed the value of the dynamic_dns_crontab_stride, so we
    # remove all existing crontab entries before creating new ones. When we do
    # this we allow for the possibility that there is an existing crontab entry
    # for every minute past the hour. There may not be but that doesn't matter.
    # The task will just skip those minutes for which there is no entry.
    - name: Clear the existing crontab entries
      ansible.builtin.cron:
        name: "Dynamic DNS update at {{ item }} minutes past the hour"
        state: absent
      with_sequence: start=0 end=59 stride=1

    - name: Add crontab entries for the dynamic-dns script
      ansible.builtin.cron:
        job: perl /usr/local/src/dynamic-dns.pl
        minute: "{{ item }}"
        name: "Dynamic DNS update at {{ item }} minutes past the hour"
      with_sequence: >-
        start=0
        end={{ 60 - dynamic_dns_crontab_stride }}
        stride={{ dynamic_dns_crontab_stride }}

    - name: Create a directory to hold dynamic DNS record configuration files
      ansible.builtin.file:
        path: "{{ dynamic_dns_records_dir }}"
        state: directory
        mode: u=rw,g=,o=

  become: yes
