# ------------------------------------------------------------------------------
# monitor_client/tasks/configure-service.yml
# ------------------------------------------------------------------------------

---

- name: Test if /etc/telegraf/telegraf.conf.sample file is present
  ansible.builtin.stat:
    path: /etc/telegraf/telegraf.conf.sample
  register: sample_config

- block:

    - name: Generate my starting Telegraf configuration
      ansible.builtin.shell: >-
        telegraf config
        --input-filter cpu:disk:mem:net:swap
        --output-filter influxdb_v2
        > /etc/telegraf/telegraf.conf
        && rm /etc/telegraf/telegraf.conf.sample
      when: sample_config.stat.exists
      notify: Telegraf configuration changed

    - name: Configure URL for influxdb access
      ansible.builtin.lineinfile:
        path: /etc/telegraf/telegraf.conf
        line: "  urls = [\"https://influxdb.{{ home_domain }}:8086\"]"
        regex: "\
          ^  urls = \\[\\\"https?://\
          (?:127\\.0\\.0\\.1|influxdb(?:\\.{{ home_domain | regex_escape }})?)\
          :8086\\\"\\]$"
      notify: Telegraf configuration changed

    - name: Configure token for influxdb access
      ansible.builtin.lineinfile:
        path: /etc/telegraf/telegraf.conf
        line: '  token = "{{ influx_access_token }}"'
        regex: '^  token = \".*\"$'
      notify: Telegraf configuration changed

    - name: Configure organisation for influxdb access
      ansible.builtin.lineinfile:
        path: /etc/telegraf/telegraf.conf
        line: '  organization = "{{ home_organisation }}"'
        regex: "\
          ^  organization = \"(?:{{ home_organisation | regex_escape }})?\"$"
      notify: Telegraf configuration changed

    - name: Configure bucket for influxdb access
      ansible.builtin.lineinfile:
        path: /etc/telegraf/telegraf.conf
        line: '  bucket = "monitor"'
        regex: '^  bucket = "(?:monitor)?"$'
      notify: Telegraf configuration changed

    - name: Disable CA verification for external connections
      ansible.builtin.lineinfile:
        path: /etc/telegraf/telegraf.conf
        line: '  insecure_skip_verify = true'
        regex: '^  (?:# )insecure_skip_verify = (?:false|true)?$'
      notify: Telegraf configuration changed

  become: yes