# ------------------------------------------------------------------------------
# monitor_client/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_tasks: install-service.yml

- ansible.builtin.import_tasks: configure-service.yml

- name: Start the telegraf service
  ansible.builtin.service:
    name: telegraf
    state: started
  become: yes
