
---

- block:

  - name: Create operating system user accounts if the domain is our own
    ansible.builtin.shell:
      cmd: >-
        useradd
        --create-home {{ user.fname }}
        --password `mkpasswd --method=md5 {{ user.passwd }}`
      creates: "/home/{{ user.fname }}"
    when: user.fname != admin_user
    loop: "{{ domain_users }}"
    loop_control:
      loop_var: user

  - name: Add alias for user to the /etc/aliases file
    ansible.builtin.lineinfile:
      path: /etc/aliases
      line: "{{ user.fname }}.{{ user.lname }}: {{ user.fname }}"
    notify: Run newaliases
    loop: "{{ domain_users }}"
    loop_control:
      loop_var: user

  become: yes
