# ------------------------------------------------------------------------------
# calendar/handlers/main.yml
# ------------------------------------------------------------------------------

# When the radicale service is managed by systemd, we restart or start the
# service whenever there is a configuration change.

---

- block:

    - name: Determine the status of the radicale service
      ansible.builtin.service_facts:
      listen: Radicale configuration changed

    # The systemd radicale unit does not support reload, so we must restart it
    # if it is running or start it if it isn't running in order to reflect
    # configuration change.

    - name: >-
        Restart the radicale service if it is running to reflect configuration
        change
      ansible.builtin.service:
        name: radicale
        state: restarted
      when: ansible_facts['services']['radicale']['state'] == 'running'
      listen: Radicale configuration changed

    - name: >-
        Start the radicale service if it isn't running to reflect configuration
        change
      ansible.builtin.service:
        name: radicale
        state: restarted
      when: ansible_facts['services']['radicale']['state'] == 'stopped'
      listen: Radicale configuration changed

  become: yes
