# ------------------------------------------------------------------------------
# calendar/handlers/main.yml
# ------------------------------------------------------------------------------

# When the radicale service is managed by systemd, we restart the service
# whenever there is a configuration change.

---

- name: Restart Radicale to reflect configuration change
  service:
    name: radicale
    state: restarted
  become: yes
  listen: Radicale configuration changed

- debug:
    msg: If you are seeing this message then something has gone wrong
  listen: Bacula file daemon installed
  when: false
