# Restart the radicale service to reflect a change to its configuration.
# NOTE: There is no reload option for the radicale service.

---

- name: Restart Radicale to reflect configuration change
  service:
    name: radicale
    state: restarted
  become: yes
  listen: Radicale configuration changed

- debug:
    msg: If you are seeing this message then something has gone wrong
  listen: Bacula file daemon installed
  when: false
