# ------------------------------------------------------------------------------
# calendar/handlers/main.yml
# ------------------------------------------------------------------------------

# When the radicale service is managed by systemd, we restart the service
# whenever there is a configuration change.

---

- block:

    - name: Determine the status of the radicale service
      ansible.builtin.service_facts:
      listen: Radicale configuration changed

    # The systemd radicale unit does not support reload, so we must restart it
    # if it is running in order to reflect configuration change.
    - name: >-
        Restart the radicale service if it is running to reflect configuration
        change
      ansible.builtin.service:
        name: radicale
        state: restarted
      when: ansible_facts['services']['radicale']['state'] == 'running'
      listen: Radicale configuration changed

  become: yes
