# NOTE: There is no reload job type under systemctl for the mariadb.service unit
- name: Restart MariaDB service
  ansible.builtin.service:
    name: mariadb.service
    state: restarted
  become: yes
  listen: MariaDB configuration changed
