# ------------------------------------------------------------------------------
# mta/handlers/main.yml
# ------------------------------------------------------------------------------

# The main (default) handler for the mta role. This combines both the "common"
# handlers that apply whether a service manager such as systemd is present or
# not and the "service" handlers that only apply if such a service manager is
# present.

---

- ansible.builtin.import_tasks: ./common.yml

- ansible.builtin.import_tasks: ./service.yml
