# database/tasks/cover.yml

---

#-------------------------------------------------------------------------------
# Restrict a database service that is currently listening on the external
# network interfaces to only listen on the localhost network interface. We may
# do this after we have temporarily exposed the service to diagnose an issue.
#-------------------------------------------------------------------------------

- name: Cover (do NOT expose) database host on external network interface
  ansible.builtin.replace:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^(bind-address\s*=\s*)0\.0\.0\.0$'
    replace: '\g<1>127.0.0.1'
  become: yes
  notify: MariaDB configuration changed
