---

- name: Cover (do NOT expose) database host on external network interface
  ansible.builtin.replace:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^(bind-address\s*=\s*)0\.0\.0\.0$'
    replace: '\g<1>127.0.0.1'
  become: yes
  notify: restart mariadb service
