# ------------------------------------------------------------------------------
# database/tasks/create-backup-database.yml
# ------------------------------------------------------------------------------

---

- block:

    - name: Create the database for the backup director to use
      community.mysql.mysql_db:
        # This task list needs to be run on the host for the MariaDB service so
        # that it can connect using the socket.
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: bacula

    - name: Create a user for bacula to use
      # Create the account for the IP address of the host that is the target for
      # the backup_director role. This relies on the play that contains the
      # backup_director role applying to a single host only.
      community.mysql.mysql_user:
        host: "{{ backup_director_host | default('localhost') }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ backup_database_user | default('bacula') }}"
        priv: 'bacula.*:ALL'
        password: "{{ backup_database_password | default('bacula') }}"

  become: yes
