# ------------------------------------------------------------------------------
# database/tasks/create-site.yml
# ------------------------------------------------------------------------------

# Create the database for a WordPress site and an associated user account to
# access it.

---

# TODO: Obfuscate the names of the WordPress site's database and user for
# "security through obscurity".

- block:

    - name: Create database for the WordPress site
      community.mysql.mysql_db:
        # Name the database by substituting '_' for '.' in the site's server
        # name; for example database www_example_com for a site with the server
        # name www.example.com.
        name: "{{ wp_server_name | regex_replace ('\\.', '_') }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create database user for the WordPress site
      community.mysql.mysql_user:
        name: "{{ wp_server_name | regex_replace ('\\.', '_') }}"
        host: |-
          {% if wp_database_host is defined %}
          {{ inventory_hostname }}.{{ home_domain }}
          {%- else %}
          localhost
          {%- endif %}
        password: "{{ wp_database_password }}"
        priv: "\
          {{ wp_server_name | regex_replace ('\\.', '_') }}.*:ALL"
        login_unix_socket: /var/run/mysqld/mysqld.sock

  become: yes
