- ansible.builtin.include_tasks: site/delete.yml
  loop: >-
    {{
    subdomains.split(',') |
    intersect(wordpress_sites | map(attribute='subdomain'))
    }}
  loop_control:
    loop_var: subdomain
