# ------------------------------------------------------------------------------
# database/tasks/install.yml
# ------------------------------------------------------------------------------

---

- name: Install APT package(s) required by the database role
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-pymysql
    install_recommends: no
  become: yes
