- name: Get the current value if it exists for the current theme mod
  ansible.builtin.command: >-
    wp --path={{ wordpress_site_path }}
    theme mod get {{ theme_mod.name }} --format=json
  changed_when: false
  register: wp_theme_mod_get

- name: Set variable current_theme_mod
  ansible.builtin.set_fact:
    current_theme_mod: "{{ wp_theme_mod_get.stdout | from_json | first }}"

- name: Set the theme mod value if it isn't the desired value
  ansible.builtin.command: >-
    wp --path={{ wordpress_site_path }}
    theme mod set {{ theme_mod.name }} {{ theme_mod.value }}
  when: current_theme_mod.value != theme_mod.value
